/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Bm(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/models/bm.glb") as any;
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            position={[1.41, 0.79, -0.86]}
            rotation={[Math.PI / 2, 0, -1.97]}
          >
            <mesh
              geometry={nodes.Object_4.geometry}
              material={nodes.Object_4.material}
            />
          </group>
          <group
            position={[-1.39, 1.76, 0.58]}
            rotation={[Math.PI / 2, 0, -1.97]}
          >
            <mesh
              geometry={nodes.Object_6.geometry}
              material={nodes.Object_6.material}
            />
          </group>
          <group
            position={[0.04, 1.71, -2.21]}
            rotation={[Math.PI / 2, 0, -1.97]}
          >
            <mesh
              geometry={nodes.Object_8.geometry}
              material={nodes.Object_8.material}
            />
          </group>
          <group position={[-0.28, 0.66, -0.5]}>
            <primitive object={nodes.GLTF_created_0_rootJoint} />
            <skinnedMesh
              geometry={nodes.Object_13.geometry}
              material={materials["Material.001"]}
              skeleton={nodes.Object_13.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_14.geometry}
              material={materials.cateye}
              skeleton={nodes.Object_14.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/bm.glb");
