/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: impoimpo (https://sketchfab.com/impoimpo)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/elon-musk-running-6ad4bbc11db84e29aa270089d143b38c
title: Elon Musk Running
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function ElonMusk({ ...props }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "/models/elon_musk_running/scene.gltf"
  ) as any;
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group scale={0.02}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <primitive object={nodes._rootJoint} />
            <group
              position={[0, -2.9, 158.42]}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <skinnedMesh
              geometry={nodes.bow_tie_bow_tie_0.geometry}
              material={materials.bow_tie}
              skeleton={nodes.bow_tie_bow_tie_0.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Blazer_Blazer_0.geometry}
              material={materials.Blazer}
              skeleton={nodes.Blazer_Blazer_0.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Henley_Longsleeve_Henley_Longsleeve_0.geometry}
              material={materials.Henley_Longsleeve}
              skeleton={nodes.Henley_Longsleeve_Henley_Longsleeve_0.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Jeans_Jeans_0.geometry}
              material={materials.Jeans}
              skeleton={nodes.Jeans_Jeans_0.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Boots_Boots_0.geometry}
              material={materials.Boots}
              skeleton={nodes.Boots_Boots_0.skeleton}
            />
            <skinnedMesh
              geometry={nodes.CC_Base_Body1_Std_Skin_Head_0.geometry}
              material={nodes.CC_Base_Body1_Std_Skin_Head_0.material}
              skeleton={nodes.CC_Base_Body1_Std_Skin_Head_0.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Hair_a_embed_hair_male_0.geometry}
              material={materials.embed_hair_male}
              skeleton={nodes.Hair_a_embed_hair_male_0.skeleton}
            />
            <skinnedMesh
              geometry={nodes.CC_Base_Eye_eyes_0.geometry}
              material={materials.eyes}
              skeleton={nodes.CC_Base_Eye_eyes_0.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Hair_embed_hair_male1_0.geometry}
              material={materials["embed_hair_male.1"]}
              skeleton={nodes.Hair_embed_hair_male1_0.skeleton}
            />
            <skinnedMesh
              geometry={nodes.hands_Std_Skin_Head_0.geometry}
              material={nodes.hands_Std_Skin_Head_0.material}
              skeleton={nodes.hands_Std_Skin_Head_0.skeleton}
            />
            <skinnedMesh
              geometry={nodes.hands_Fingernail_0.geometry}
              material={materials.Fingernail}
              skeleton={nodes.hands_Fingernail_0.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/elon_musk_running/scene.gltf");
