/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function ElonMuskRunning({ ...props }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "/models/elon_musk_running/elon_musk_running.glb"
  ) as any;
  const { actions, names } = useAnimations(animations, group);
  // Change animation when the index changes
  useEffect(() => {
    // Reset and fade in animation after an index has been changed
    actions[names?.[0]]?.reset().fadeIn(0.5).play();
    // In the clean-up phase, fade it out
    return () => {
      actions[names?.[0]]?.fadeOut(0.5);
    };
  }, [actions, names]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group scale={0.02}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <primitive object={nodes._rootJoint} />
            <group
              position={[0, -2.9, 158.42]}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <skinnedMesh
              geometry={nodes.Blazer_Blazer_0.geometry}
              material={materials.Blazer}
              skeleton={nodes.Blazer_Blazer_0.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Boots_Boots_0.geometry}
              material={materials.Boots}
              skeleton={nodes.Boots_Boots_0.skeleton}
            />
            <skinnedMesh
              geometry={nodes.bow_tie_bow_tie_0.geometry}
              material={materials.bow_tie}
              skeleton={nodes.bow_tie_bow_tie_0.skeleton}
            />
            <skinnedMesh
              geometry={nodes.CC_Base_Body1_Std_Skin_Head_0.geometry}
              material={nodes.CC_Base_Body1_Std_Skin_Head_0.material}
              skeleton={nodes.CC_Base_Body1_Std_Skin_Head_0.skeleton}
            />
            <skinnedMesh
              geometry={nodes.CC_Base_Eye_eyes_0.geometry}
              material={materials.eyes}
              skeleton={nodes.CC_Base_Eye_eyes_0.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Hair_a_embed_hair_male_0.geometry}
              material={materials.embed_hair_male}
              skeleton={nodes.Hair_a_embed_hair_male_0.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Hair_embed_hair_male1_0.geometry}
              material={materials["embed_hair_male.1"]}
              skeleton={nodes.Hair_embed_hair_male1_0.skeleton}
            />
            <skinnedMesh
              geometry={nodes.hands_Fingernail_0.geometry}
              material={materials.Fingernail}
              skeleton={nodes.hands_Fingernail_0.skeleton}
            />
            <skinnedMesh
              geometry={nodes.hands_Std_Skin_Head_0.geometry}
              material={nodes.hands_Std_Skin_Head_0.material}
              skeleton={nodes.hands_Std_Skin_Head_0.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Henley_Longsleeve_Henley_Longsleeve_0.geometry}
              material={materials.Henley_Longsleeve}
              skeleton={nodes.Henley_Longsleeve_Henley_Longsleeve_0.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Jeans_Jeans_0.geometry}
              material={materials.Jeans}
              skeleton={nodes.Jeans_Jeans_0.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/elon_musk_running/elon_musk_running.glb");
