/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: hamsterspit (https://sketchfab.com/hamsterspit)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/d6921528881c4776a38a35ba52e328c6
title: Medieval asset 13\ money bag
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function MoneyBag({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/models/money_bag/scene.gltf") as any;
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            position={[1.85, 21.19, -2.73]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Money_bag_asset_assets_texture_0.geometry}
              material={materials.assets_texture}
            />
            <mesh
              geometry={nodes.Money_bag_asset_coin_0.geometry}
              material={materials.coin}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/money_bag/scene.gltf");
