/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Frank Murphy (https://sketchfab.com/KaboomAnimations)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/mario-fire-flower-0055b438b52e4bab97ebc40c41b63654
title: Mario Fire Flower
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Rangeup({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF(
    "/models/mario_fire_flower/scene.gltf"
  ) as any;
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} position={[0, 2, 0]} scale={0.4}>
        <group position={[4.08, 1.01, 5.9]} rotation={[-0.27, 0.6, 1.93]} />
        <group position={[-0.34, 0.17, 0.45]} scale={[0.56, 1.58, 1.32]}>
          <mesh
            geometry={nodes.Sphere_0.geometry}
            material={materials["Material.002"]}
          />
        </group>
        <group
          position={[-0.48, 0.17, 0.41]}
          rotation={[2.67, -1.47, 1.39]}
          scale={[1.56, 1.53, 1.59]}
        >
          <mesh
            geometry={nodes.Torus_0.geometry}
            material={materials["Material.003"]}
          />
        </group>
        <group
          position={[-0.44, 0.2, 0.45]}
          rotation={[2.67, -1.47, 1.39]}
          scale={[2.25, 2.21, 3.02]}
        >
          <mesh
            geometry={nodes.Torus001_0.geometry}
            material={materials["Material.004"]}
          />
        </group>
        <group position={[0.08, 0.63, 0.6]} scale={[0.39, 0.28, 0.56]}>
          <mesh
            geometry={nodes.Sphere001_0.geometry}
            material={nodes.Sphere001_0.material}
          />
        </group>
        <group position={[0.08, -0.26, 0.6]} scale={[0.39, 0.28, 0.56]}>
          <mesh
            geometry={nodes.Sphere002_0.geometry}
            material={nodes.Sphere002_0.material}
          />
        </group>
        <group
          position={[-0.61, 1.32, -3]}
          rotation={[0.5, 0.89, 2.89]}
          scale={[0.68, 0.91, 0.68]}
        >
          <mesh
            geometry={nodes.Sphere004_0.geometry}
            material={materials["Material.006"]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/mario_fire_flower/scene.gltf");
